// Optional: requires playwright and an installed Chromium browser.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const {spawn}=require('node:child_process');
const {mkdtempSync,rmSync}=require('node:fs');
const {join,resolve}=require('node:path');
const {tmpdir}=require('node:os');
const dataDir=mkdtempSync(join(tmpdir(),'proyecta-browser-'));
const child=spawn(process.env.PYTHON||'python3',[resolve(__dirname,'../app.py'),'--no-browser','--port','0','--data-dir',dataDir]);
child.on('close',()=>rmSync(dataDir,{recursive:true,force:true}));
process.on('exit',()=>child.kill());
(async()=>{
 const base=await new Promise((resolve,reject)=>{let out='';child.stdout.on('data',s=>{out+=s;const m=out.match(/http:\/\/127\.0\.0\.1:\d+/);if(m)resolve(m[0])});child.on('error',reject)});
 const browser=await chromium.launch({headless:true,args:['--no-sandbox'],executablePath:process.env.CHROMIUM_EXECUTABLE||undefined});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto(base);
 await page.getByRole('button',{name:'Cargar ejemplos'}).click();
 await page.getByRole('heading',{name:'RIPO',exact:true}).waitFor();
 await page.getByRole('button',{name:'+ Nuevo proyecto'}).click();
 await page.getByLabel('Nombre del proyecto').fill('Proyecta');
 await page.getByLabel('Objetivo actual').fill('Reunir el estado y las decisiones de mis proyectos.');
 await page.getByLabel('Próxima acción').fill('Instalar versión 1 en Linux Mint.');
 await page.getByRole('button',{name:'Guardar',exact:true}).click();
 await page.getByRole('heading',{name:'Proyecta',exact:true}).waitFor();
 await page.locator('#toast').evaluate(e=>e.style.display='none');
 await page.screenshot({path:join(dataDir,'PORTAFOLIO.png'),fullPage:true});
 await page.locator('article.card').filter({has:page.getByRole('heading',{name:'Proyecta',exact:true})}).getByRole('button',{name:'Abrir proyecto'}).click();
 await page.getByRole('button',{name:'+ Nueva tarea',exact:true}).click();
 await page.getByLabel('Título',{exact:true}).fill('Validar instalación Mint');
 await page.getByLabel('Necesita mi atención').check();
 await page.getByRole('button',{name:'Guardar',exact:true}).click();
 await page.getByText('Validar instalación Mint',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Editar',exact:true}).click();
 await page.getByLabel('Estado',{exact:true}).selectOption('completada');
 await page.getByRole('button',{name:'Guardar',exact:true}).click();
 await page.locator('#form-error').filter({hasText:'Registra evidencia'}).waitFor();
 await page.getByLabel('Evidencia o resultado').fill('Prueba de interfaz: flujo completo verificado en entorno Linux de ejecución. No probado aún en Mint.');
 await page.getByRole('button',{name:'Guardar',exact:true}).click();
 await page.locator('#content').getByText('Completada',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Decisiones',exact:true}).click();
 await page.getByRole('button',{name:'+ Registrar',exact:true}).click();
 await page.getByLabel('Decisión, trabajo o resultado').fill('Linux Mint primero; conservar portabilidad entre sistemas.');
 await page.getByRole('button',{name:'Guardar',exact:true}).click();
 await page.getByText('Linux Mint primero; conservar portabilidad entre sistemas.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Preparar contexto para IA'}).click();
 await page.locator('#context-preview').filter({hasText:'Linux Mint primero'}).waitFor();
 await page.getByLabel('Consultar registros de este proyecto').fill('¿Qué sigue?');
 await page.getByRole('button',{name:'Consultar',exact:true}).click();
 await page.locator('#ask-answer').filter({hasText:'Instalar versión 1 en Linux Mint.'}).waitFor();
 await page.locator('#toast').evaluate(e=>e.style.display='none');
 await page.screenshot({path:join(dataDir,'CONTEXTO.png'),fullPage:true});
 await page.getByRole('button',{name:'Necesita mi atención'}).click();
 assert.equal(await page.getByText('Validar instalación Mint',{exact:true}).count(),0);
 // Stored inputs render as text, never HTML.
 await page.getByRole('button',{name:'Portafolio',exact:false}).click();
 await page.getByRole('button',{name:'+ Nuevo proyecto'}).click();
 await page.getByLabel('Nombre del proyecto').fill('<img src=x onerror=alert(1)>');
 await page.getByRole('button',{name:'Guardar',exact:true}).click();
 await page.getByRole('heading',{name:'<img src=x onerror=alert(1)>',exact:true}).waitFor();
 assert.equal(await page.locator('article.card img').count(),0);
 await page.getByRole('searchbox').fill('Cognitia');
 assert.equal(await page.locator('article.card').count(),1);
 await page.getByRole('searchbox').fill('');
 // Remove the intentional XSS test record from demo screenshots via backup restoration.
 await page.evaluate(async()=>{const state=await(await fetch('/api/state')).json();const bad=state.projects.find(p=>p.name.startsWith('<img')).id;state.projects=state.projects.filter(p=>p.id!==bad);state.tasks=state.tasks.filter(t=>t.project_id!==bad);state.events=state.events.filter(e=>e.project_id!==bad);const token=(await(await fetch('/api/session')).json()).token;await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/json','X-Proyecta-Token':token},body:JSON.stringify(state)});});
 await page.reload();await page.getByRole('heading',{name:'Proyecta',exact:true}).waitFor();
 // Responsive layout and restore affordance.
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:join(dataDir,'MOVIL.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);
 await page.locator('#restore-mobile').waitFor({state:'visible'});
 await page.reload();await page.getByRole('heading',{name:'Proyecta',exact:true}).waitFor();
 // The deliberate completion without evidence returns one expected HTTP 400.
 assert.deepEqual(errors,['Failed to load resource: the server responded with a status of 400 (Bad Request)']);
 console.log('UI OK: creación/edición, evidencia, decisiones, consulta, atención, XSS, búsqueda, recarga y móvil.');
 await browser.close();
 child.kill();
})().catch(e=>{console.error(e);process.exit(1)});
